remote_theme: jekyll-theme-slate
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
name: digital-twins
description: Bookmark this to keep an eye on my project updates!
gem "github-pages", group: :jekyll_plugins
